### ISSUE TITLE
"get in touch" text difficult to read

### ISSUE THREAD

**Issue by jarantfos** [EditLLC/client-carter-meeting#10]
possible solution: place the text within a transparent box over the image increasing readability

**Comment by rodneystrong** [comment]
I'll post a CSS option that might work.

**Comment by rodneystrong** [comment]
Here's a good article about this: https://css-tricks.com/design-considerations-text-images/

I want you to implement the second option that's titled "White Text" for all the sections in that have this problem

**Comment by jarantfos** [comment]
applied the white text fix to everything relevant
