### ISSUE TITLE
Images are large

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-carter-meeting#11]
The images from the issue #10 where you had to manipulate the text for those sections are over 1MB each. 

https://www.shopify.com/blog/7412852-10-must-know-image-optimization-tips  Read # 4 on that page. 

As a rule of thumb, try to get the images under 500kb each without losing too much detail. 

due:
1-7-16  3p

**Comment by jarantfos** [comment]
All images were optimized to be ~500-600kb

**Comment by rodneystrong** [comment]
Good stuff. Please merge this into the gh-pages branch and push

**Comment by jarantfos** [comment]
Whoops, I swear I did that... lemme fix
