### ISSUE TITLE
Clean up the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-carter-meeting#3]
Make the contact form at the top be all the same height and aligned 

Remove that random 'r' that's chillin here: 
![r](https://cloud.githubusercontent.com/assets/539962/9451436/895775ce-4a63-11e5-949c-a5840ed3dc33.jpg)

These icons are off-center; please center them to the page:

![off](https://cloud.githubusercontent.com/assets/539962/9451458/a43c1b60-4a63-11e5-9a9e-bffcb50c9634.jpg)

Look at the site as a whole and fix anything you think isn't presentable. Obviously the missing content isn't something we can do much about right now, but the aforementioned issues as well as any similar issues are what we're trying to fix here.  Please fix any details that wouldn't look presentable. 

due:
8-29-15   11p

**Comment by vanderbeam** [comment]
Alex!! This completely slipped through the cracks!! So sorry...
I fixed the r, corrected the image locations, centers the our service items, corrected the navigation, and changed the contact under the slider (which I am still not a fan of but it looks better than it did).  Also changed the brand padding so the nav wouldn't overlap.

**Comment by rodneystrong** [comment]
It happens Meg, and no worries. Just remember to set up a system that helps you stay on top of these due dates. 

Also, please remember to merge this into your gh-pages branch as well so we can easily see the changes live on a URL. 

Don't worry, I already merged your changes and uploaded the updated gh-pages branch.
