### ISSUE TITLE
Start site build from scratch

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-carter-meeting#4]
Put in site content where you think it's intuitive. 

Get the word doc from our google drive; file should be titled "website content" in the "Ccarter Meeting" folder. 

due:
12-14-15    5p

**Comment by jarantfos** [comment]
I copied over all the content from the drive and made some minor changes to the site to accommodate.

**Comment by rodneystrong** [comment]
Good stuff. Could you do me a big favor and create a gh-pages branch as well? Be sure to push the new branch.

**Comment by jarantfos** [comment]
Sure thing

**Comment by jarantfos** [comment]
gh-pages is up to date now. The task is mostly done but I still have a few minor things to do like find unique icons for each <i> tag.

**Comment by jarantfos** [comment]
I finished and pushed everything you suggested on the site, and I think it looks pretty nice now. If you have any more changes, please let me know, otherwise, I think I finished the task

**Comment by rodneystrong** [comment]
good stuff Jared. thanks for doin this.
